"""add_reviews_and_total_score

Revision ID: 705b7ebb8af0
Revises: b933d4ed741b
Create Date: 2026-09-29 02:30:35.692971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '705b7ebb8af0'
down_revision: Union[str, Sequence[str], None] = 'b933d4ed741b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('quest_id', sa.Uuid(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['quest_id'], ['quests.id'], name=op.f('fk_reviews_quest_id_quests'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_reviews_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviews')),
    sa.UniqueConstraint('id', name=op.f('uq_reviews_id'))
    )
    op.create_unique_constraint(op.f('uq_media_id'), 'media', ['id'])
    op.create_unique_constraint(op.f('uq_questions_id'), 'questions', ['id'])
    op.create_unique_constraint(op.f('uq_quests_id'), 'quests', ['id'])
    op.create_unique_constraint(op.f('uq_quiz_options_id'), 'quiz_options', ['id'])
    op.create_unique_constraint(op.f('uq_steps_id'), 'steps', ['id'])
    op.create_unique_constraint(op.f('uq_user_progress_id'), 'user_progress', ['id'])
    op.create_unique_constraint(op.f('uq_user_purchases_id'), 'user_purchases', ['id'])
    op.add_column('users', sa.Column('total_lifetime_score', sa.Integer(), nullable=False))
    op.create_unique_constraint(op.f('uq_users_id'), 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_id'), 'users', type_='unique')
    op.drop_column('users', 'total_lifetime_score')
    op.drop_constraint(op.f('uq_user_purchases_id'), 'user_purchases', type_='unique')
    op.drop_constraint(op.f('uq_user_progress_id'), 'user_progress', type_='unique')
    op.drop_constraint(op.f('uq_steps_id'), 'steps', type_='unique')
    op.drop_constraint(op.f('uq_quiz_options_id'), 'quiz_options', type_='unique')
    op.drop_constraint(op.f('uq_quests_id'), 'quests', type_='unique')
    op.drop_constraint(op.f('uq_questions_id'), 'questions', type_='unique')
    op.drop_constraint(op.f('uq_media_id'), 'media', type_='unique')
    op.drop_table('reviews')
    # ### end Alembic commands ###
